# .github/workflows/**main.yml**
name: Django-app workflow

on: [push]

jobs:
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # Запуск actions checkout — готового скрипта 
    # для клонирования репозитория
    - uses: actions/checkout@v2
    - name: Set up Python
      # Запуск actions setup-python — готового скрипта 
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        # Выбор версии Python
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # обновление pip
        python -m pip install --upgrade pip 
        # установка flake8 и его плагинов
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установка зависимостей
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py — 
        #<корневая_папка_infra_actions>/<папка_проекта>/manage.py
        cd infra_project/
        # запустить написанные разработчиком тесты
        python manage.py test
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflowyy
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: brutiq/infra_actions:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBte1ajtl
WwBEwqeCnN3DJfAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCqhiggz835
4Vv0KbZV4/9lshCyqCSnL1W1cBOGk2JQfAu1otjGTlAvHb8y2TE1WMGTLmFi75aggMjG9t
zR7X/gAP+Z+7vYb+ezIdnqhOMm5Gsxg9QFt/uxgCC6Z6+nqZPb1ehLe03FDU+XGd4n5OPn
BRtc4Krf1voU7nEPcWLU7MAd5Bwrf4ersgsCrtlEKFl7vVUBtfzCe1Z0o0GZjFD+I3GTCZ
0R4djy9XKpTsFc7ouakX0k3SoLDy6ctBwHf2f4Oceu9A/oAd5IvW60WhmxH6KF/yl6VcSH
I0SevDigSkRfVEk5P6yw11D/sb1DTrUSpoQi4f8i3ri7Y+ibFh4HQ2yG0vgVVp+f5hKK6x
RJJfUMtfsNikoDY6r8fRlaMG6t3cqozMpQaqzdQgpEbHOrKvd3+V4G4WTIxixHCz2xQgVB
p93KVtZAsCMHy6U6AOP9Kw7t2yRvxC+EiPZdLiGcrV331t8TfQMYqy9OAeVNZXIQY3Pjs7
rnh5t0oURr4SEAAAWQLwf6VN9tQwGxlxZOXqf1S7v8lsdqjj+trF2AJxysyKAErlfeS8h7
8HhEfggM0R0e9wN5SIzr3jHa7Le3FpYWHxfTP701G8PHQDKLUdrV8MJo6SL9BaZpw/XYNR
gAouueMmfcpr9Eu+rqdG6AQxb5qgF72FvmrewyjfReDxHi+K121hZu962gHZVWcAaCQhCk
2yiu/miTP/iA1cDpHJA6cmHhWbK7zy5ltQUa3MAetn8nJE0E4HVNyBpbVdn2xRWjDgjgCk
ak4Bvxr0jZc7AR/RTIxels/Sjcwwg/I0FzXnSQ1YCw853l9vuMkBKr67zJRYJ2PGVRnGTQ
W/BknR+6G6ozeHzUrJGb2PifHfXmBFZdCwIJTXGwm0czogi8RJnbuCFUpp3JMaV2LKMcbe
K6R1xHwCdPStR+TC4j6762PDVkJcd+obBuQjIohAc4oXk3I7GbRibJvkqDgeeNe512fFOp
PZfpZrLnb4rQfwPVyp27O+sd6DqA4E8n/06ABkwiePmUYKJ9SCMaYTb4DxEhJXzZQMb0ae
O/RyOcpG4fOLLOkiLDlsmsh6zyb5Jwh7qqn5C6HdfrkUIBLQMmla9J9ONgGFXpK6hdAI9k
xDGnxp+nrgAtQSsZYWuFCO8sg6tVllt3WhxZc+chg99yR8FFbCEs9CVm98Wi3qveaaVwv3
Tciij9FV7UCs36aUQfT/8S7aHOSvmLUFs8I4WoQDQkzF70dQ4o2jStXGhlvuHHOhJqnBux
v9Xls/8OqH0nmuAoqbZlDr89OappYAjPy2rj4bfvxLB8cjWXx4UGLNHYg4dQdlX2rvagGS
/0vyHYZMUTESh8EkG0CA+u52WJg+n8Q9PgUsm0NFk2jjz4oce8XLS1Klh4/uVYWVRVDBh4
7gpz/yihZnnLzCWjKk/W25+cwnfCe/LRXVYvwqLLL08UB8kSzbwAnGYOz4AfWfv1g9v2pf
dBU6svbfi6OCtYGLz9utgPE72pyxUOz94TO2SNaxSyw4VCiqgBIy8rGwGzmi4TdiLfgN7Y
oo6mxZQt4fElg6rc2e2pxBgK/Zkv46EKEUwSTzKJ6C7TriHmj6icCy6KCzMNmpieZ1teRN
OnKiRZtpmeCZ0ow0sYz9vrXKML3acHs/m3qFwJ8ouSjSxzar+uek5hicpzKvQNvzQe99P1
CCBDNpYeXrRT4kDHTxTilwrb4qHZIxZr3UxHD5CVr9vGP9Xes5lwTOqHZdHwrNXI+8Ot1j
hFrnBKmqDhlzS3u3xgHqKofvNhAa6z5W2zLswRWRWpCHEwq2Id3EV9HV/9tsooUPg5kl65
D6cs1epVcR/wijbphz7VZiiRUCXQH4Angi2xqB0heyVdn6wGfFbla+wrGjrPhqHfPTchiE
qolKbzmmGA3ADvVDQCz8Fgw3HFyR8xID2X9EWa1maLTwUe4oBOJN8JpQbUd50dAyq6yG0e
CiH9lgdxMK17PrVPpkw86ABbyGS+29V6I347pIVqd9TeePFHiKrTt9VbMGCBGz1JnC3OP6
MO1MD2MLpdf8iTJsCurby2Q+irBMOSaHZ1ff38Rco+6pbds+hvDxr5BHxB4GuL9LTh4X0E
twIjaDmrFL9BZon1sZN53zGBDmxj4hqCmS1YlYMMXaoS1Ebeu/nGaIPXrGHA9+Cf8DMBi7
oT1aBcbKimZagwWbdflFdEtzsh5b9JOK++p15epduqLsvJTVCJ9txhqdE97AIyA/pt+Zvf
y5+AuNN5sMOYqO/b/09iMsXFOWVmOsdHELXuYSWqnJY9SVRLyI9/fzkdlBtoze7nyUA/D/
s1v09CDJDCqjJncShDWF5cYXU0KaJukEiXqJ17zNPU8M3XAab1D+DlHe9lKgB5cpQCNBui
ABfnK0eIAPCrXP6ARh9GtDygRNU=
        script: |
          # Выполняет pull образа с DockerHub
          sudo docker pull brutiq/infra_actions
          #остановка всех контейнеров
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker run --rm -d -p 5000:5000 brutiq/infra_actions
